app/user/__init__.py
from flask import Blueprint

user_blueprint = Blueprint('users', __name__, url_prefix='/users')

from app.user import views

app/user/views.py
from app.model import User, db
from flask import render_template, request, redirect, url_for
from app.user import user_blueprint

@user_blueprint.route("/landing", endpoint="land")
def land():
    users = User.query.all()
    return render_template("users/landing.html", users=users)

@user_blueprint.route("/show/<int:id>", endpoint="show_user")
def show(id):
    user = User.query.get(id)  # Changed from users to user to match singular form
    return render_template("users/show.html", user=user)  # Changed variable name to user

@user_blueprint.route("/delete/<int:id>", endpoint="delete_user")
def delete_user(id):
    user = User.query.get(id)  # Changed from users to user to match singular form
    if user:
        db.session.delete(user)
        db.session.commit()
    return redirect(url_for("user_blueprint.land"))

@user_blueprint.route("/create", endpoint="create_user", methods=['GET', "POST"])
def create():
    if request.method == "POST":
        user = User(
            username=request.form['username'],  
            age=request.form['age'],
            image=request.form['image']
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("user_blueprint.land"))
    return render_template("users/create.html")

@user_blueprint.route("/edit/<int:id>", endpoint="edit_user", methods=['GET', "POST"])
def edit(id):
    user = User.query.get(id) 
    if request.method == "POST":
        user.username = request.form['username'] 
        user.age = request.form['age']
        user.image = request.form['image']
        db.session.commit()
        return redirect(url_for("user_blueprint.land"))
    return render_template("users/edit.html", user=user)  

app/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('posts.land')}}">Posts</a>
        </li>
       <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('posts.create_post')}}">Creat</a>
        </li>

      </ul>

    </div>
  </div>
</nav>

<div class="container">
    {% block content  %}

    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

app/templates/users/create.html
{% extends './base.html' %}

{% block title %}Create user{% endblock %}

{% block content %}
  <h1 style="text-align: center"> Add new user</h1>

  <form method="POST" action="{{ url_for('user_blueprint.create_user') }}">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>
    <label for="age">Age:</label>
    <input type="number" id="age" name="age" required>
    <label for="image">Image URL:</label>
    <input type="text" id="image" name="image" required>
    <input type="submit" value="Create User">
</form>

{% endblock %}

app/templates/users/edit.html
{% extends './base.html' %}

{% block title %}Edit users{% endblock %}

{% block content %}
  <h1 style="text-align: center"> Edit the users</h1>

  <form method="POST" action="{{ url_for('user_blueprint.edit_user', id=user.id) }}">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" value="{{ user.username }}" required>
    <label for="age">Age:</label>
    <input type="number" id="age" name="age" value="{{ user.age }}" required>
    <label for="image">Image URL:</label>
    <input type="text" id="image" name="image" value="{{ user.image }}" required>
    <input type="submit" value="Update User">
</form>

{% endblock %}

app/templates/users/landing.html
  {% extends "./base.html" %}
  {% block title %} Landing Page{% endblock %}

  {% block content%}


    <table class="table">

        <tr>
          <td>  <h3>id</h3></td>
          <td>  <h3>name</h3></td>
          <td>  <h3>age</h3></td>
          <td>  <h3>image</h3></td>
          <td>  <h3>action </h3></td>
        </tr>

        {% for u in users%}
            <tr>
                <td>{{u.id}}</td>
                <td>{{u.name}}</td>
                <td>{{u.age}}</td>
                <td> <img src="{{u.image_url_user}}"  width="100" height="100" ></td>
                <td>
                    <a href="{{url_for('users.show_user', id=u.id)}}" class="btn btn-info" >Show</a>
                    <a href="{{url_for('users.edit_user', id=u.id)}}" class="btn btn-dark" >Edite</a>
                    <a href="{{url_for('users.delete_user', id=u.id)}}" class="btn btn-danger" >Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a style="text-align: center" href="{{url_for('users.create_user')}}" class="btn btn-info w-75 h-50" >Create New user</a>

      {%endblock%}

app/templates/users/show.html
{% extends "./base.html" %} {% block title %} Show Page{% endblock %} {% block
content%}
<h1>
  show details of user
</h1>
    <div class="card d-flex justify-content-center shadow w-25 h-25">

      <img src="{{users.image_url_user}}" class="card-img-top" />
      <h3 class="card-title m-3">user number : {{users.id}}</h3>
      <h3 class="card-title m-3">{{users.name}}</h3>

      <p class="card-text m-3">{{users.age}}</p>
    </div>

    {%endblock%}