app/posts/__init__.py
from flask import  Blueprint

posts_blueprint = Blueprint('posts', __name__, url_prefix='/posts')

from app.posts import  views

app/posts/api/views.py
from flask_restful import Resource, Api, marshal_with
from app.posts.api.serializers import post_serializer
from app.posts.api.parsers import posts_parser
from app.model import Post, db
class GetPosts(Resource):
    @marshal_with(post_serializer)
    def get(self):                                   #Retrieves all post obj from db
        posts=Post.query.all()
        return posts

    @marshal_with(post_serializer)
    def post(self):
        post_arg=posts_parser.parse_args()
        posts=Post(**post_arg)
        db.session.add(posts)
        db.session.commit()
        return posts

class PostsResourse(Resource):
    @marshal_with(post_serializer)
    def get(self, id):                     #Retrieves a single Post object by its id
        # post = db.get_or_404(post, id)
        posts =Post.query.get(id)
        return posts

    @marshal_with(post_serializer)
    def put(self, id):
        posts = Post.query.get(id)
        post_args = posts_parser.parse_args()
        posts.name = post_args['name']
        posts.descrip = post_args['descrip']
        posts.image = post_args['image']
        posts.user_id = post_args['user_id']
        db.session.add(posts)
        db.session.commit()
        return posts

    @marshal_with(post_serializer)
    def delete(self, id):
        posts = Post.query.get(id)
        db.session.delete(posts)
        db.session.commit()
        return "this post is deleted"
    

app/posts/views.py
from app.model import Post, db, User
from flask import render_template, request, redirect, url_for
from app.posts import posts_blueprint
from app.posts.form import PostForm


@posts_blueprint.route("/landing", endpoint="land")
def land():
    posts=Post.query.all()
    # return redirect(url_for('posts_land'))
    return  render_template("posts/landing.html", posts=posts)


@posts_blueprint.route("/show/<int:id>", endpoint="show_post")
def show(id):
    posts = Post.query.get(id)
    return render_template("posts/show.html", posts=posts)


@posts_blueprint.route("/delete/<int:id>", endpoint="delete_post")
def delete_post(id):
    post = Post.query.get(id)
    if post:
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for("posts.land"))


@posts_blueprint.route("/create", endpoint="create_post", methods=['GET', "POST"])
def create():
    users=User.query.all()
    if request.method == "POST":
        post = Post(name=request.form['name'],
                    descrip=request.form['descrip'],
                    image=request.form['image'],
                    user_id=request.form['user_id'])

        db.session.add(post)
        db.session.commit()
        return redirect(url_for("posts.land"))
    return render_template("posts/create.html",users=users)


@posts_blueprint.route("/edit/<int:id>", endpoint="edit_post", methods=['GET', "POST"])
def edit(id):
    post = Post.query.get(id)
    if request.method == "POST":
        post.name = request.form['name']
        post.descrip = request.form['descrip']
        post.image = request.form['image']
        post.user_id=request.form['user_id']
        db.session.commit()
        return redirect(url_for("posts.land"))
    return render_template("posts/edit.html", post=post)



import os
from werkzeug.utils import secure_filename
from app.posts.form import PostForm
@posts_blueprint.route("/for/create", endpoint="Form_Create" ,methods=['GET', "POST"])
def create_post_form():
    form = PostForm()
    if request.method == "POST":
        if form.validate_on_submit():
            if form.image.data:
                image= form.image.data
                image_name =secure_filename(image.filename)
                image_path = os.path.join('static/images/', image_name)
                image.save(image_path)

            post = Post(name=request.form['name'],
                    descrip=request.form['descrip'],
                    image=image_name,
                    user_id=request.form['user_id'])
            db.session.add(post)
            db.session.commit()
        return redirect(url_for("posts.land"))
    return render_template("posts/form/FormCreate.html",form=form )

app/templates/posts/create.html
{% extends './base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1 class="text-center mb-4">Add New Post</h1>

    <form method="POST">
      <div class="row mb-3">
        <div class="col-md-6">
          <label class="form-label" for="postName">Name</label>
          <input type="text" id="postName" name="name" class="form-control" required>
        </div>
        <div class="col-md-6">
          <label class="form-label" for="postImage">Image</label>
          <input type="text" id="postImage" name="image" class="form-control" required>
        </div>
      </div>

      <div class="mb-3">
        <label class="form-label" for="postDescription">Description</label>
        <textarea id="postDescription" name="descrip" class="form-control" rows="4" required></textarea>
      </div>

      <div class="mb-3">
        <label class="form-label" for="postUser">User</label>
        <select id="postUser" class="form-select" name="user_id" required>
          <option value="" disabled selected>Select a user</option>
          {% for u in users %}
            <option value="{{ u.id }}">{{ u.username }}</option>
          {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-primary w-100">Add Post</button>
    </form>
  </div>
{% endblock %}

app/templates/posts/edit.html
{% extends './base.html' %}

{% block title %}Edit post{% endblock %}

{% block content %}
  <h1 style="text-align: center"> Edit the Post</h1>

<form method="post" >
  <div class="mb-3">

    <label class="form-label">Name</label>
    <input type="text" name="name" class="form-control" value="{{post.name}}">
  </div>
 <div class="mb-3">
    <label class="form-label">Image</label>
    <input type="text" name="image" class="form-control"  value="{{post.image}}">
  </div>
  <div class="mb-3">
    <label class="form-label">description</label>
    <input type="text" name="descrip" class="form-control"  value="{{post.descrip}}">
  </div>
  <button type="submit" class="btn btn-info w-100">Edit</button>
</form>
{% endblock %}

app/templates/posts/landing.html
  {% extends "./base.html" %}
  {% block title %} Landing Page{% endblock %}

  {% block content%}


    <table class="table">

        <tr>
          <td>  <h3>id</h3></td>
          <td>  <h3>name</h3></td>
          <td>  <h3>description</h3></td>
          <td>  <h3>image</h3></td>
          <td> <h3>user_id</h3></td>
          <td>  <h3>action </h3></td>
        </tr>

        {% for p in posts%}
            <tr>
                <td>{{p.id}}</td>
                <td>{{p.name}}</td>
                <td>{{p.descrip}}</td>
                <td> <img src="{{p.image_url}}"  width="100" height="100" ></td>
                <td>{{p.user_id}}</td>
                <td>
                    <a href="{{url_for('posts.show_post', id=p.id)}}" class="btn btn-info" >Show</a>
                    <a href="{{url_for('posts.edit_post', id=p.id)}}" class="btn btn-dark" >Edite</a>
                    <a href="{{url_for('posts.delete_post', id=p.id)}}" class="btn btn-danger" >Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a style="text-align: center" href="{{url_for('posts.create_post')}}" class="btn btn-info w-75 h-50" >Create New Post</a>

      {%endblock%}
    </h1>
  </h1>
</html>

app/templates/posts/show.html
{% extends "./base.html" %} {% block title %} Show Page{% endblock %} {% block
content%}
<h1>
  show details of post
</h1>
    <div class="card d-flex justify-content-center shadow w-25 h-25">

      <img src="{{posts.image_url}}" class="card-img-top" />
      <h3 class="card-title m-3">post number : {{posts.id}}</h3>
      <h3 class="card-title m-3">{{posts.name}}</h3>

      <p class="card-text m-3">{{posts.descrip}}</p>
        <p class="card-text m-3">{{posts.user_id}}</p>
    </div>

    {%endblock%}